version: "3.4"

services:
  unleash:
    container_name: unleash
    image: unleashorg/unleash-proxy
    restart: always
    ports:
      - "3030:3000"
    environment:
      UNLEASH_URL: <API URL from GitLab>
      UNLEASH_INSTANCE_ID: <Instance ID from GitLab>
      UNLEASH_APP_NAME: staging
      UNLEASH_PROXY_SECRETS: MY_UNLEASH_PROXY_SECRETS
      UNLEASH_API_TOKEN: _
